# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: 
  schedule:
      - cron: "* 12 */2 * *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with: 
         node-version: "14"
    - run: npm install
    - run: npm run update-readme     
    - run: |
       git config user.name lololopez200123
       git config user.email lololopez200123@gmail.com
       git pull
       git add .
       git commit -m "[bot] add actual Readme"
       git push origin main
